/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package codapplication;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTabbedPane;

/**
 *
 * @author Aslam Odayappurath
 */
public class MainMenuForm extends javax.swing.JPanel {

    /**
     * Creates new form MainMenuForm2
     */
    public MainMenuForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LoginButton = new javax.swing.JButton();
        menuTab = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        itemName1 = new javax.swing.JLabel();
        itemPrice1 = new javax.swing.JLabel();
        itemCheck1 = new javax.swing.JCheckBox();
        itemName2 = new javax.swing.JLabel();
        itemPrice2 = new javax.swing.JLabel();
        itemCheck2 = new javax.swing.JCheckBox();
        itemName3 = new javax.swing.JLabel();
        itemPrice3 = new javax.swing.JLabel();
        itemCheck3 = new javax.swing.JCheckBox();
        itemName4 = new javax.swing.JLabel();
        itemPrice4 = new javax.swing.JLabel();
        itemCheck4 = new javax.swing.JCheckBox();
        itemName5 = new javax.swing.JLabel();
        itemPrice5 = new javax.swing.JLabel();
        itemCheck5 = new javax.swing.JCheckBox();
        itemName6 = new javax.swing.JLabel();
        itemPrice6 = new javax.swing.JLabel();
        itemCheck6 = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        itemName7 = new javax.swing.JLabel();
        itemPrice7 = new javax.swing.JLabel();
        itemCheck7 = new javax.swing.JCheckBox();
        jSeparator13 = new javax.swing.JSeparator();
        addBreakfast = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        starterLabel = new javax.swing.JLabel();
        starterItem1 = new javax.swing.JLabel();
        starterPrice1 = new javax.swing.JLabel();
        starterCheck1 = new javax.swing.JCheckBox();
        starterItem2 = new javax.swing.JLabel();
        starterPrice2 = new javax.swing.JLabel();
        starterCheck2 = new javax.swing.JCheckBox();
        starterItem3 = new javax.swing.JLabel();
        starterPrice3 = new javax.swing.JLabel();
        starterCheck3 = new javax.swing.JCheckBox();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        mainLabel = new javax.swing.JLabel();
        mainItem1 = new javax.swing.JLabel();
        mainPrice1 = new javax.swing.JLabel();
        mainCheck1 = new javax.swing.JCheckBox();
        jSeparator8 = new javax.swing.JSeparator();
        mainItem2 = new javax.swing.JLabel();
        mainPrice2 = new javax.swing.JLabel();
        mainCheck2 = new javax.swing.JCheckBox();
        mainItem3 = new javax.swing.JLabel();
        dessertPrice1 = new javax.swing.JLabel();
        mainCheck3 = new javax.swing.JCheckBox();
        jSeparator9 = new javax.swing.JSeparator();
        dessertLabel = new javax.swing.JLabel();
        dessertItem1 = new javax.swing.JLabel();
        mainPrice4 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        dessertCheck1 = new javax.swing.JCheckBox();
        dessertItem2 = new javax.swing.JLabel();
        dessertPrice2 = new javax.swing.JLabel();
        dessertCheck2 = new javax.swing.JCheckBox();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        addBreakfast1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lunchMainLabel = new javax.swing.JLabel();
        lunchMain1 = new javax.swing.JLabel();
        lunchPrice1 = new javax.swing.JLabel();
        lunchItemSelect1 = new javax.swing.JCheckBox();
        lunchMain2 = new javax.swing.JLabel();
        lunchPrice2 = new javax.swing.JLabel();
        lunchItemSelect2 = new javax.swing.JCheckBox();
        lunchMain3 = new javax.swing.JLabel();
        lunchPrice3 = new javax.swing.JLabel();
        lunchItemSelect3 = new javax.swing.JCheckBox();
        lunchMain4 = new javax.swing.JLabel();
        lunchPrice4 = new javax.swing.JLabel();
        lunchItemSelect4 = new javax.swing.JCheckBox();
        lunchMain5 = new javax.swing.JLabel();
        lunchPrice5 = new javax.swing.JLabel();
        lunchItemSelect5 = new javax.swing.JCheckBox();
        lunchMain6 = new javax.swing.JLabel();
        lunchPrice7 = new javax.swing.JLabel();
        lunchItemSelect6 = new javax.swing.JCheckBox();
        lunchMain7 = new javax.swing.JLabel();
        lunchPrice8 = new javax.swing.JLabel();
        lunchItemSelect7 = new javax.swing.JCheckBox();
        addDinner = new javax.swing.JButton();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        jSeparator19 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setFocusTraversalPolicyProvider(true);
        jPanel1.setPreferredSize(new java.awt.Dimension(1050, 650));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Main Menu");

        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        menuTab.setBackground(new java.awt.Color(255, 255, 255));
        menuTab.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        itemName1.setText("Lemony radish & fennel salad");

        itemPrice1.setText("£6.59 ");

        itemCheck1.setBackground(new java.awt.Color(255, 255, 255));
        itemCheck1.setText("Select Item");
        itemCheck1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCheck1ActionPerformed(evt);
            }
        });

        itemName2.setText("The ultimate makeover: Full English breakfast");

        itemPrice2.setText("£13.00 ");

        itemCheck2.setBackground(new java.awt.Color(255, 255, 255));
        itemCheck2.setText("Select Item");
        itemCheck2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCheck2ActionPerformed(evt);
            }
        });

        itemName3.setText("Cinnamon buckwheat pancakes with cherries");

        itemPrice3.setText("£7.20");

        itemCheck3.setBackground(new java.awt.Color(255, 255, 255));
        itemCheck3.setText("Select Item");
        itemCheck3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCheck3ActionPerformed(evt);
            }
        });

        itemName4.setText("Rye bread with almond butter & pink grapefruit segments");

        itemPrice4.setText("£4.89 ");

        itemCheck4.setBackground(new java.awt.Color(255, 255, 255));
        itemCheck4.setText("Select Item");
        itemCheck4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCheck4ActionPerformed(evt);
            }
        });

        itemName5.setText("Smoky rashers & tomatoes on toast");

        itemPrice5.setText("£4.89 ");

        itemCheck5.setBackground(new java.awt.Color(255, 255, 255));
        itemCheck5.setText("Select Item");
        itemCheck5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCheck5ActionPerformed(evt);
            }
        });

        itemName6.setText("Cinnamon pancakes with compote & maple syrup");

        itemPrice6.setText("£7.20 ");

        itemCheck6.setBackground(new java.awt.Color(255, 255, 255));
        itemCheck6.setText("Select Item");
        itemCheck6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCheck6ActionPerformed(evt);
            }
        });

        itemName7.setText("Cheesy scrambled egg croissants");

        itemPrice7.setText("£3.75");

        itemCheck7.setBackground(new java.awt.Color(255, 255, 255));
        itemCheck7.setText("Select Item");
        itemCheck7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCheck7ActionPerformed(evt);
            }
        });

        addBreakfast.setText("Add Selected ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(itemName2)
                            .addComponent(itemName1)
                            .addComponent(itemName4)
                            .addComponent(itemName3)
                            .addComponent(itemName5)
                            .addComponent(itemName6)
                            .addComponent(itemName7))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(itemPrice4)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(itemPrice7)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(itemPrice2)
                                            .addComponent(itemPrice1)
                                            .addComponent(itemPrice3)
                                            .addComponent(itemPrice5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(itemCheck5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(itemCheck1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(itemCheck2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(itemCheck3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(itemCheck4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(itemPrice6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(itemCheck6, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(101, 101, 101))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator13, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(itemCheck7, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(101, 101, 101))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addBreakfast)
                .addGap(113, 113, 113))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemName1)
                    .addComponent(itemPrice1)
                    .addComponent(itemCheck1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemName2)
                    .addComponent(itemPrice2)
                    .addComponent(itemCheck2))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemName3)
                    .addComponent(itemPrice3)
                    .addComponent(itemCheck3))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemName4)
                    .addComponent(itemPrice4)
                    .addComponent(itemCheck4))
                .addGap(12, 12, 12)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemName5)
                    .addComponent(itemPrice5)
                    .addComponent(itemCheck5))
                .addGap(16, 16, 16)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemName6)
                    .addComponent(itemPrice6)
                    .addComponent(itemCheck6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemPrice7)
                    .addComponent(itemName7)
                    .addComponent(itemCheck7))
                .addGap(18, 18, 18)
                .addComponent(addBreakfast)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuTab.addTab("Breakfast Menu", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        starterLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        starterLabel.setText("Starter");

        starterItem1.setText("Mini prawn & sweetcorn cakes");

        starterPrice1.setText("£4.80");

        starterCheck1.setBackground(new java.awt.Color(255, 255, 255));
        starterCheck1.setText("Select Item");

        starterItem2.setText("Pea & savory soup");

        starterPrice2.setText("£3.50");

        starterCheck2.setBackground(new java.awt.Color(255, 255, 255));
        starterCheck2.setText("Select Item");

        starterItem3.setText("Beetroot, goat's cheese & anchovy salad ");

        starterPrice3.setText("£4.59 ");

        starterCheck3.setBackground(new java.awt.Color(255, 255, 255));
        starterCheck3.setText("Select Item");

        mainLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mainLabel.setText("Main");

        mainItem1.setText("One-pan duck with Savoy cabbage");

        mainPrice1.setText("£9.89");

        mainCheck1.setBackground(new java.awt.Color(255, 255, 255));
        mainCheck1.setText("Select Item");

        mainItem2.setText("Pan-fried salmon ");

        mainPrice2.setText("£10.59");

        mainCheck2.setBackground(new java.awt.Color(255, 255, 255));
        mainCheck2.setText("Select Item");

        mainItem3.setText("Slow-roast pork belly with celeriac & pear mash ");

        dessertPrice1.setText("4.30");

        mainCheck3.setBackground(new java.awt.Color(255, 255, 255));
        mainCheck3.setText("Select Item");

        dessertLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dessertLabel.setText("Dessert");

        dessertItem1.setText("Peach Melba trifle");

        mainPrice4.setText("£9.75");

        dessertCheck1.setBackground(new java.awt.Color(255, 255, 255));
        dessertCheck1.setText("Select Item");

        dessertItem2.setText("Blueberry & lime cheesecake");

        dessertPrice2.setText("£4.97");

        dessertCheck2.setBackground(new java.awt.Color(255, 255, 255));
        dessertCheck2.setText("Select Item");

        addBreakfast1.setText("Add Selected ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(starterLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(dessertLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator12, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator10, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator9, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator8)
                            .addComponent(jSeparator11, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(starterItem1)
                                    .addComponent(starterItem2)
                                    .addComponent(starterItem3)
                                    .addComponent(mainLabel)
                                    .addComponent(mainItem1)
                                    .addComponent(mainItem2)
                                    .addComponent(mainItem3))
                                .addGap(91, 194, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(mainPrice4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(mainCheck3))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(mainPrice2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 417, Short.MAX_VALUE)
                                        .addComponent(mainCheck2))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(mainPrice1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(mainCheck1))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(starterPrice3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(starterCheck3))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(starterPrice2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(starterCheck2))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(starterPrice1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(starterCheck1))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(dessertItem1)
                                        .addGap(340, 340, 340)
                                        .addComponent(dessertPrice1))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(dessertItem2)
                                        .addGap(286, 286, 286)
                                        .addComponent(dessertPrice2)))
                                .addGap(91, 423, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dessertCheck1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(dessertCheck2, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(addBreakfast1)))
                        .addGap(31, 31, 31))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(starterLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(starterItem1)
                    .addComponent(starterPrice1)
                    .addComponent(starterCheck1))
                .addGap(3, 3, 3)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(starterPrice2)
                        .addComponent(starterCheck2))
                    .addComponent(starterItem2))
                .addGap(1, 1, 1)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(starterPrice3)
                        .addComponent(starterCheck3))
                    .addComponent(starterItem3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(mainLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainItem1)
                    .addComponent(mainPrice1)
                    .addComponent(mainCheck1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainPrice2)
                    .addComponent(mainCheck2)
                    .addComponent(mainItem2))
                .addGap(4, 4, 4)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainItem3)
                    .addComponent(mainCheck3)
                    .addComponent(mainPrice4))
                .addGap(18, 18, 18)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dessertLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dessertCheck2)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dessertItem1))
                                .addComponent(dessertCheck1))
                            .addComponent(dessertPrice1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dessertItem2)
                            .addComponent(dessertPrice2))
                        .addGap(7, 7, 7)))
                .addGap(32, 32, 32)
                .addComponent(addBreakfast1)
                .addGap(22, 22, 22))
        );

        menuTab.addTab("Lunch Menu", jPanel4);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lunchMainLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lunchMainLabel.setText("Main");

        lunchMain1.setText("Grilled Polenta");

        lunchPrice1.setText("£4.80");

        lunchItemSelect1.setBackground(new java.awt.Color(255, 255, 255));
        lunchItemSelect1.setText("Select Item");

        lunchMain2.setText("Macaroni Cheese Fritter");

        lunchPrice2.setText("£12.50");

        lunchItemSelect2.setBackground(new java.awt.Color(255, 255, 255));
        lunchItemSelect2.setText("Select Item");

        lunchMain3.setText("Curried Mackerel");

        lunchPrice3.setText("£19.50");

        lunchItemSelect3.setBackground(new java.awt.Color(255, 255, 255));
        lunchItemSelect3.setText("Select Item");

        lunchMain4.setText("Lobster Lasagne");

        lunchPrice4.setText("£25.00");

        lunchItemSelect4.setBackground(new java.awt.Color(255, 255, 255));
        lunchItemSelect4.setText("Select Item");

        lunchMain5.setText("Chermoula Spiced Poussin");

        lunchPrice5.setText("£18.00");

        lunchItemSelect5.setBackground(new java.awt.Color(255, 255, 255));
        lunchItemSelect5.setText("Select Item");

        lunchMain6.setText("Roasted Pork Loin");

        lunchPrice7.setText("£15.50");

        lunchItemSelect6.setBackground(new java.awt.Color(255, 255, 255));
        lunchItemSelect6.setText("Select Item");

        lunchMain7.setText("Longhorn Beef & Bone Marrow Burger ");

        lunchPrice8.setText("£20.00");

        lunchItemSelect7.setBackground(new java.awt.Color(255, 255, 255));
        lunchItemSelect7.setText("Select Item");

        addDinner.setText("Add Selected ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addDinner))
                    .addComponent(jSeparator14)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lunchMainLabel)
                                    .addComponent(lunchMain7))
                                .addGap(216, 216, 216)
                                .addComponent(lunchPrice8))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lunchMain1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lunchPrice1)
                                .addGap(231, 231, 231))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lunchMain2)
                                .addGap(284, 284, 284)
                                .addComponent(lunchPrice2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lunchMain3)
                                .addGap(319, 319, 319)
                                .addComponent(lunchPrice3))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lunchMain4)
                                .addGap(320, 320, 320)
                                .addComponent(lunchPrice4))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lunchMain5)
                                .addGap(276, 276, 276)
                                .addComponent(lunchPrice5))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lunchMain6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 313, Short.MAX_VALUE)
                                .addComponent(lunchPrice7)
                                .addGap(226, 226, 226)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lunchItemSelect1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lunchItemSelect2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lunchItemSelect3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lunchItemSelect4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lunchItemSelect5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lunchItemSelect6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lunchItemSelect7, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jSeparator15, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator16, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator17, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator18, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator19, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(123, 123, 123))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lunchMainLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lunchMain1)
                        .addComponent(lunchPrice1))
                    .addComponent(lunchItemSelect1))
                .addGap(13, 13, 13)
                .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lunchMain2)
                    .addComponent(lunchPrice2)
                    .addComponent(lunchItemSelect2))
                .addGap(13, 13, 13)
                .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lunchMain3)
                    .addComponent(lunchPrice3)
                    .addComponent(lunchItemSelect3))
                .addGap(9, 9, 9)
                .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lunchMain4)
                    .addComponent(lunchPrice4)
                    .addComponent(lunchItemSelect4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lunchMain5)
                    .addComponent(lunchPrice5)
                    .addComponent(lunchItemSelect5))
                .addGap(9, 9, 9)
                .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lunchMain6)
                    .addComponent(lunchPrice7)
                    .addComponent(lunchItemSelect6))
                .addGap(8, 8, 8)
                .addComponent(jSeparator19, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lunchMain7)
                    .addComponent(lunchPrice8)
                    .addComponent(lunchItemSelect7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(addDinner)
                .addGap(48, 48, 48))
        );

        menuTab.addTab("Dinner Menu", jPanel2);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 993, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 503, Short.MAX_VALUE)
        );

        menuTab.addTab("Daily Specials", jPanel6);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 993, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 503, Short.MAX_VALUE)
        );

        menuTab.addTab("Drinks", jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(288, 288, 288)
                .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuTab, javax.swing.GroupLayout.PREFERRED_SIZE, 1002, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuTab, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed

    }//GEN-LAST:event_LoginButtonActionPerformed

    private void itemCheck6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCheck6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemCheck6ActionPerformed

    private void itemCheck5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCheck5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemCheck5ActionPerformed

    private void itemCheck4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCheck4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemCheck4ActionPerformed

    private void itemCheck3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCheck3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemCheck3ActionPerformed

    private void itemCheck2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCheck2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemCheck2ActionPerformed

    private void itemCheck1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCheck1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemCheck1ActionPerformed

    private void itemCheck7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCheck7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemCheck7ActionPerformed

 
  

    public JButton getLoginButton() {
        return LoginButton;
    }
    

    

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginButton;
    private javax.swing.JButton addBreakfast;
    private javax.swing.JButton addBreakfast1;
    private javax.swing.JButton addDinner;
    private javax.swing.JCheckBox dessertCheck1;
    private javax.swing.JCheckBox dessertCheck2;
    private javax.swing.JLabel dessertItem1;
    private javax.swing.JLabel dessertItem2;
    private javax.swing.JLabel dessertLabel;
    private javax.swing.JLabel dessertPrice1;
    private javax.swing.JLabel dessertPrice2;
    private javax.swing.JCheckBox itemCheck1;
    private javax.swing.JCheckBox itemCheck2;
    private javax.swing.JCheckBox itemCheck3;
    private javax.swing.JCheckBox itemCheck4;
    private javax.swing.JCheckBox itemCheck5;
    private javax.swing.JCheckBox itemCheck6;
    private javax.swing.JCheckBox itemCheck7;
    private javax.swing.JLabel itemName1;
    private javax.swing.JLabel itemName2;
    private javax.swing.JLabel itemName3;
    private javax.swing.JLabel itemName4;
    private javax.swing.JLabel itemName5;
    private javax.swing.JLabel itemName6;
    private javax.swing.JLabel itemName7;
    private javax.swing.JLabel itemPrice1;
    private javax.swing.JLabel itemPrice2;
    private javax.swing.JLabel itemPrice3;
    private javax.swing.JLabel itemPrice4;
    private javax.swing.JLabel itemPrice5;
    private javax.swing.JLabel itemPrice6;
    private javax.swing.JLabel itemPrice7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JCheckBox lunchItemSelect1;
    private javax.swing.JCheckBox lunchItemSelect2;
    private javax.swing.JCheckBox lunchItemSelect3;
    private javax.swing.JCheckBox lunchItemSelect4;
    private javax.swing.JCheckBox lunchItemSelect5;
    private javax.swing.JCheckBox lunchItemSelect6;
    private javax.swing.JCheckBox lunchItemSelect7;
    private javax.swing.JLabel lunchMain1;
    private javax.swing.JLabel lunchMain2;
    private javax.swing.JLabel lunchMain3;
    private javax.swing.JLabel lunchMain4;
    private javax.swing.JLabel lunchMain5;
    private javax.swing.JLabel lunchMain6;
    private javax.swing.JLabel lunchMain7;
    private javax.swing.JLabel lunchMainLabel;
    private javax.swing.JLabel lunchPrice1;
    private javax.swing.JLabel lunchPrice2;
    private javax.swing.JLabel lunchPrice3;
    private javax.swing.JLabel lunchPrice4;
    private javax.swing.JLabel lunchPrice5;
    private javax.swing.JLabel lunchPrice7;
    private javax.swing.JLabel lunchPrice8;
    private javax.swing.JCheckBox mainCheck1;
    private javax.swing.JCheckBox mainCheck2;
    private javax.swing.JCheckBox mainCheck3;
    private javax.swing.JLabel mainItem1;
    private javax.swing.JLabel mainItem2;
    private javax.swing.JLabel mainItem3;
    private javax.swing.JLabel mainLabel;
    private javax.swing.JLabel mainPrice1;
    private javax.swing.JLabel mainPrice2;
    private javax.swing.JLabel mainPrice4;
    private javax.swing.JTabbedPane menuTab;
    private javax.swing.JCheckBox starterCheck1;
    private javax.swing.JCheckBox starterCheck2;
    private javax.swing.JCheckBox starterCheck3;
    private javax.swing.JLabel starterItem1;
    private javax.swing.JLabel starterItem2;
    private javax.swing.JLabel starterItem3;
    private javax.swing.JLabel starterLabel;
    private javax.swing.JLabel starterPrice1;
    private javax.swing.JLabel starterPrice2;
    private javax.swing.JLabel starterPrice3;
    // End of variables declaration//GEN-END:variables
}
